### ISSUE TITLE
 print "ERROR: Make sure you have .env file with proper config"

### ISSUE THREAD

**Issue by r1eki** [meibenjin/GoogleSearchCrawler#18]
Googlesearchcrawler not support python 3.6 ? Because when execution "python gsearch.py "indonesia" appear an error " print "ERROR: Make sure you have .env file with proper config""

**Comment by meibenjin** [comment]
> Googlesearchcrawler not support python 3.6 ? Because when execution "python gsearch.py "indonesia" appear an error " print "ERROR: Make sure you have .env file with proper config""

in order to load .env config , you should rename .env.example to .env
