### ISSUE TITLE
error: 'module' object is not callable

### ISSUE THREAD

**Issue by loveJasmine** [meibenjin/GoogleSearchCrawler#20]
ub16hp@UB16HP:/media/ub16hp/WINDOWS/ub16_prj/GoogleSearchCrawler$ python3 gsearch.py
error: 'module' object is not callable

error: 'module' object is not callable
error: 'module' object is not callable

**Comment by ahangarha** [comment]
You should use python version 2 to run this code

Python 3 support is not implemented yet
