### ISSUE TITLE
how to solve this error

### ISSUE THREAD

**Issue by jenindra** [meibenjin/GoogleSearchCrawler#22]
File "gsearch.py", line 35
    print "ERROR: Make sure you have .env file with proper config"
                                                                 ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("ERROR: Make sure you have .env file with proper config")?

**Comment by ahangarha** [comment]
You are running it with python 3 which requires parentheses for `print` function. Run the script with python 2.7

**Comment by jenindra** [comment]
thank you
