### ISSUE TITLE
Doesn't print unless I remove reload(sys) sys.setdefaultencoding('utf-8')

### ISSUE THREAD

**Issue by macdonjo** [meibenjin/GoogleSearchCrawler#3]
I had to comment out the following lines to get any output or print statements to work.

#reload(sys)
#sys.setdefaultencoding('utf-8')

**Comment by yingzhang** [comment]
I would like to output 100 retrieved results , however,it just can retrieve 10 results and repeat them 10 times...

**Comment by caengcjd** [comment]
error: junk characters in start tag: u'{t:119}); class=gbzt', at line 1, column
45190 
ohhhhh,I'm  crazy

**Comment by meibenjin** [comment]
你不是在爬google的搜索结果吧,有可能是中文的问题, 你加我qq吧 971445581

**Comment by BachWings** [comment]
我爬google搜索结果的话，返回503是ip被ban掉了吗

**Comment by meibenjin** [comment]
503错误一般是服务器端出错，有可能是网络的问题
