### ISSUE TITLE
HTTP Error 503: Service Unavailable

### ISSUE THREAD

**Issue by psegovias** [meibenjin/GoogleSearchCrawler#5]
python gsearch.py 
url error: HTTP Error 503: Service Unavailable

Any idea?

**Comment by haozhec** [comment]
perhaps your IP is banned, could you please change your IP and try again?

**Comment by Luckystrike561** [comment]
I have the same problem.
I changed my ip but I have the same  error -> "url error: HTTP Error 503: Service Unavailable".

**Comment by xujiaqing2016** [comment]
the first time i run the program it is ok, and then i meet the same problem too. but  the url in my firefox is ok.
how could i do now?

**Comment by HipHopAllen** [comment]
I met the same issue and don't know how to solve it.

**Comment by guangyue** [comment]
I met the same issue and don't know how to solve it.

**Comment by szjhtz** [comment]
好像已经无效了,爬取不了数据了.

**Comment by meibenjin** [comment]
> 好像已经无效了,爬取不了数据了.

google可能已经修改了页面的结构，其他用户报了这个问题，我修复了一下，但是现在我连不上google，你那边可以测试下吗

**Comment by ahangarha** [comment]
I have received the same error on another script. I seems it is not related to the script itself.
