### ISSUE TITLE
Can you please adjust to python3?

### ISSUE THREAD

**Issue by AssafMalki** [meibenjin/GoogleSearchCrawler#8]
First of all, thanks a lot.
I got the following error
error: initial_value must be str or None, not bytes
after adjusting the code to python3 and I'm not sure what is the issue.

I have attached the changes I did.

[gsearch.zip](https://github.com/meibenjin/GoogleSearchCrawler/files/489208/gsearch.zip)

**Comment by meibenjin** [comment]
I'm sorry to answer you so late, here I found the problem: http://stackoverflow.com/questions/31064981/python3-error-initial-value-must-be-str-or-none
