### ISSUE TITLE
I am not able to see any result,is there any problem ,plz help me

### ISSUE THREAD

**Issue by tiru1930** [meibenjin/GoogleSearchCrawler#9]
Vostro-3446:~/Downloads/GoogleSearchCrawler-master$ python gsearch.py  "PYTHON"
tiru@tiru-Vostro-3446:~/Downloads/GoogleSearchCrawler-master$

**Comment by elisezhao** [comment]
I cannot see the result either. Do anyone of you find the result? Where is it saved?

**Comment by meibenjin** [comment]
It's will print on the screen.

**Comment by meibenjin** [comment]
duplicate issue #11
